/* eslint-disable no-undef */
/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      screens: {
        md: "769px",
        lg: "1025px",
      },
      colors: {
        darkBlue: "#151542",
        lightWhite: "#f7f7f7",
        customGray: "#686868",
        "theme-color": "var(--theme-color)",
        "bg-blank": "var(--bg-blank)",
        "funnel-theme-color": "var(--funnel-theme-color)",
        "theme-alter-color": "var(--theme-alter-color)",
        "theme-filter-color": "var(--theme-filter-color)",
        "dark-theme-color": "var(--dark-theme-color)",
        "filter-border-color": "var(--filter-border-color)",
        "theme-search-color": "var(--theme-search-color)",
        "table-header-color": "var(--table-header-color)",
        "footer-theme-color": "var(--footer-theme-color)",
        "model-overlay-color": "var(--model-overlay-color)",
        "grayscale-0": "var(--grayscale-0)",
        "grayscale-100": "var(--grayscale-100)",
        "grayscale-20": "var(--grayscale-20)",
        "grayscale-200": "var(--grayscale-200)",
        "grayscale-2100": "var(--grayscale-2100)",
        "grayscale-2200": "var(--grayscale-2200)",
        "grayscale-2300": "var(--grayscale-2300)",
        "grayscale-2400": "var(--grayscale-2400)",
        "grayscale-2500": "var(--grayscale-2500)",
        "grayscale-2600": "var(--grayscale-2600)",
        "grayscale-2700": "var(--grayscale-2700)",
        "grayscale-2800": "var(--grayscale-2800)",
        "grayscale-2900": "var(--grayscale-2900)",
        "grayscale-300": "var(--grayscale-300)",
        "grayscale-400": "var(--grayscale-400)",
        "grayscale-500": "var(--grayscale-500)",
        "grayscale-600": "var(--grayscale-600)",
        "grayscale-700": "var(--grayscale-700)",
        "grayscale-800": "var(--grayscale-800)",
        "grayscale-900": "var(--grayscale-900)",
      },
      fontFamily: {
        body: ['"Poppins"'],
        "heading-h1-bold": "var(--heading-h1-bold-font-family)",
        "heading-h1-medium": "var(--heading-h1-medium-font-family)",
        "heading-h1-regular": "var(--heading-h1-regular-font-family)",
        "heading-h1-semibold": "var(--heading-h1-semibold-font-family)",
        "heading-h2-bold": "var(--heading-h2-bold-font-family)",
        "heading-h2-medium": "var(--heading-h2-medium-font-family)",
        "heading-h2-regular": "var(--heading-h2-regular-font-family)",
        "heading-h2-semibold": "var(--heading-h2-semibold-font-family)",
        "heading-h3-bold": "var(--heading-h3-bold-font-family)",
        "heading-h3-medium": "var(--heading-h3-medium-font-family)",
        "heading-h3-regular": "var(--heading-h3-regular-font-family)",
        "heading-h3-semibold": "var(--heading-h3-semibold-font-family)",
        "paregraph-p1-bold": "var(--paregraph-p1-bold-font-family)",
        "paregraph-p1-medium": "var(--paregraph-p1-medium-font-family)",
        "paregraph-p1-regular": "var(--paregraph-p1-regular-font-family)",
        "paregraph-p1-semibold": "var(--paregraph-p1-semibold-font-family)",
        "paregraph-p2-bold": "var(--paregraph-p2-bold-font-family)",
        "paregraph-p2-medium": "var(--paregraph-p2-medium-font-family)",
        "paregraph-p2-regular": "var(--paregraph-p2-regular-font-family)",
        "paregraph-p2-semibold": "var(--paregraph-p2-semibold-font-family)",
        "paregraph-p3-bold": "var(--paregraph-p3-bold-font-family)",
        "paregraph-p3-medium": "var(--paregraph-p3-medium-font-family)",
        "paregraph-p3-regular": "var(--paregraph-p3-regular-font-family)",
        "paregraph-p3-semibold": "var(--paregraph-p3-semibold-font-family)",
      },
      fontSize: {
        sm: "14px",
        xsm: "12px",
      },
      boxShadow: {
        custom: "-8px 8px 16px 0px rgba(0, 0, 0, 0.15)",
      },
    },
  },
  plugins: [],
};
